# Use the official Python 3.9 slim image as a base
FROM python:3.12-slim


WORKDIR /app

RUN pip install --upgrade pip
RUN pip install pytest pytest-cov isort taskipy coverage blue

RUN apt update && apt install -y git zsh curl wget
# Default powerline10k theme, no plugins installed
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.2.0/zsh-in-docker.sh)"

COPY requirements.txt .
RUN pip install  -r requirements.txt